PRAGMA foreign_keys=ON;
CREATE TABLE school_years(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE NOT NULL,active INTEGER NOT NULL DEFAULT 0);
CREATE TABLE teachers(id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT,name TEXT NOT NULL,nip TEXT,active INTEGER DEFAULT 1);
CREATE TABLE subjects(id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT,name TEXT NOT NULL,active INTEGER DEFAULT 1);
CREATE TABLE classes(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE NOT NULL,active INTEGER DEFAULT 1);
CREATE TABLE time_slots(id INTEGER PRIMARY KEY AUTOINCREMENT,day TEXT NOT NULL,jp INTEGER NOT NULL,start_time TEXT NOT NULL,end_time TEXT NOT NULL,UNIQUE(day,jp));
CREATE TABLE schedules(
 id INTEGER PRIMARY KEY AUTOINCREMENT,school_year_id INTEGER NOT NULL,day TEXT NOT NULL,jp INTEGER NOT NULL,
 class_id INTEGER NOT NULL,subject_id INTEGER NOT NULL,teacher_id INTEGER NOT NULL,notes TEXT,
 UNIQUE(school_year_id,day,jp,class_id),
 FOREIGN KEY(school_year_id) REFERENCES school_years(id) ON DELETE CASCADE,
 FOREIGN KEY(class_id) REFERENCES classes(id) ON DELETE CASCADE,
 FOREIGN KEY(subject_id) REFERENCES subjects(id) ON DELETE RESTRICT,
 FOREIGN KEY(teacher_id) REFERENCES teachers(id) ON DELETE RESTRICT);
CREATE INDEX idx_schedule_teacher ON schedules(school_year_id,day,jp,teacher_id);
